# Generated by Django 3.2.3 on 2021-06-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_starting_bid_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list',
            new_name='date_listed',
        ),
    ]
