# Generated by Django 3.2.3 on 2021-06-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210616_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
