# Generated by Django 3.2.3 on 2021-07-26 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
